apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-getway
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-getway
  template:
    metadata:
      labels:
        app: api-getway
    spec:
        containers:
        - name: api-getway
          image: eu.gcr.io/hprofits/api-getway:latest
          args:
            - "./api-getway"
            - "api"
            - "--handler=event"
          env:
          - name: MICRO_API_ADDRESS
            value: ":80"
          - name: MICRO_BROKER
            value: "stan"
          - name: MICRO_BROKER_ADDRESS
            value: "stan:4222"
          - name: MICRO_TRANSPORT
            value: "nats"
          - name: MICRO_TRANSPORT_ADDRESS
            value: "stan:4222"
          - name: MICRO_REGISTRY
            value: "nats"
          - name: MICRO_REGISTRY_ADDRESS
            value: "stan:4222"
          - name: CORS_ALLOWED_HEADERS
            value: "*"
          - name: CORS_ALLOWED_ORIGINS
            value: "*"   
          - name: CORS_ALLOWED_METHODS
            value: "POST,OPTIONS"
          - name: UPDATED_AT
            value: "Пт фев 22 15:33:01 MSK 2019"
          ports:
          - containerPort: 8080
            name: port