apiVersion: v1
kind: Service
metadata:
  name: api-getway
spec:
  type: LoadBalancer
  ports:
  - name: api-getway-port
    port: 80
    targetPort: "port"
    protocol: TCP
  selector:
    app: api-getway